version = 1
[[annotations]]
path = "LICENSE"
SPDX-FileCopyrightText = "2026 PATCEX Ops"
SPDX-License-Identifier = "LicenseRef-PIRW-ACL-1.0"

[[annotations]]
path = "docs/**"
SPDX-FileCopyrightText = "2026 PATCEX Ops"
SPDX-License-Identifier = "LicenseRef-PIRW-ACL-1.0"
